### PR TITLE
Bump browser-polyfill to 0.1.1

### PR DESCRIPTION
**Pull request by MGHawes**
Bumping to get https://github.com/expo/browser-polyfill/pull/44 in, @EvanBacon would you be okay with this bump, the implications are small.

### CODE REVIEW

**Comment by MGHawes** [comment]
@EvanBacon sorry for the double tap here, I was wondering if we could get this bump in?

**Comment by MGHawes** [comment]
Hey @tsapeta any chance of a +1 on this, @EvanBacon seems to be pretty busy and you're the only other person i could find that had previously approved any PRs?

**Review by tsapeta — APPROVED** [review]
Thanks for taking care of it! I'm gonna merge it and then publish to npm 😉

**Comment by tsapeta** [comment]
Just published as `5.6.2` 😉 btw, I also merged some PRs from dependantbot

**Pull request merged**
